name: llhttp

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  ffi: ^2.0.1
  path: ^1.8.0

dev_dependencies:
  ffigen:
    path: '../native/pkgs/ffigen'
  lints: ^2.0.1

ffigen:
  name: http
  ffi-native:
    assetId: '../deps/llhttp/build/llhttp.h'
  description: Bindings to `llhttp.h`.
  output: 'http/generated_bindings.kk'
  headers:
    entry-points:
      - 'deps/llhttp/build/llhttp.h'
  preamble: |
    // Copyright (c) 2020, the Koka-Community authors. All rights reserved. 
    // Use of this source code is governed by a
    // MIT-style license that can be found in the LICENSE file.
  compiler-opts:
    - '-Ideps/llhttp/build'
  functions:
    exclude:
      - (_)+.*
      - .*internal.*
  structs:
    exclude:
      - (_)+.*
      - .*internal.*
      - llhttp__internal_s
    member-rename:
      '.*':
        '_(.*)': '$1'
  enums:
    exclude:
      - (_)+.*
      - .*internal.*
  unions:
    exclude:
      - (_)+.*
      - .*internal.*
  globals:
    exclude:
      - (_)+.*
      - .*internal.*
  macros:
    exclude:
      - (_)+.*
      - .*internal.*
  typedefs:
    exclude:
      - (_)+.*
      - .*internal.*